const condolencesData = [
  {
    username: "Samppa Nori",
    registered: "2012/01/01",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Estavan Lykos",
    registered: "2012/02/01",
    status: "Rejeitado",
    mensagem: "lorem ipsum",
  },
  {
    username: "Chetan Mohamed",
    registered: "2012/02/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Derick Maximinus",
    registered: "2012/03/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Friderik Dávid",
    registered: "2012/01/21",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Yiorgos Avraamu",
    registered: "2012/01/01",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Avram Tarasios",
    registered: "2012/02/01",
    status: "Rejeitado",
    mensagem: "lorem ipsum",
  },
  {
    username: "Quintin Ed",
    registered: "2012/02/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Enéas Kwadwo",
    registered: "2012/03/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Agapetus Tadeáš",
    registered: "2012/01/21",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Carwyn Fachtna",
    registered: "2012/01/01",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Nehemiah Tatius",
    registered: "2012/02/01",
    status: "Rejeitado",
    mensagem: "lorem ipsum",
  },
  {
    username: "Ebbe Gemariah",
    registered: "2012/02/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Eustorgios Amulius",
    registered: "2012/03/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Leopold Gáspár",
    registered: "2012/01/21",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Pompeius René",
    registered: "2012/01/01",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Paĉjo Jadon",
    registered: "2012/02/01",
    status: "Rejeitado",
    mensagem: "lorem ipsum",
  },
  {
    username: "Micheal Mercurius",
    registered: "2012/02/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Ganesha Dubhghall",
    registered: "2012/03/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Hiroto Šimun",
    registered: "2012/01/21",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Vishnu Serghei",
    registered: "2012/01/01",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Zbyněk Phoibos",
    registered: "2012/02/01",
    status: "Rejeitado",
    mensagem: "lorem ipsum",
  },
  {
    username: "Einar Randall",
    registered: "2012/02/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
  {
    username: "Félix Troels",
    registered: "2012/03/21",
    status: "Aceito",
    mensagem: "lorem ipsum",
  },
  {
    username: "Aulus Agmundr",
    registered: "2012/01/01",
    status: "Pendente",
    mensagem: "lorem ipsum",
  },
];

export default condolencesData;
